name: Sync Envs to GitHub Secrets

on:
  push:
    branches:
      - main
      - development
      - testing
    paths:
      - ".env.example"
  workflow_dispatch:

# The 'jobs' key starts here
jobs:
  # The job 'sync-envs' is indented under 'jobs'
  sync-envs:
    # 'runs-on', 'permissions', and 'steps' must all be at the SAME indentation level
    # directly under 'sync-envs'

    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync envs to GitHub secrets
        run: |
          while IFS='=' read -r key value
          do
            if [[ ! -z "$key" && ! "$key" =~ ^# ]]; then
              echo "➡️ Setting secret for '$key'"
              gh secret set "$key" --body "$value" --repo $GITHUB_REPOSITORY
            fi
          done < .env.example
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
